mapPackageHierarchy|me.mdbell.awtea.classlib.java=java
mapPackageHierarchy|me.mdbell.awtea.classlib.javax=javax
stripPrefixFromPackageHierarchyClasses|me.mdbell.awtea.classlib=T
includePackageHierarchy|java.sound=false
